### PR TITLE
error running `npm test`

### LINKED ISSUE #8: Running npm test produces error.
$ npm test

> issue-complete@1.1.0 test /home/tawrun/work/opensource/issue-complete
> jest && standard

 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.613s, estimated 5s
Ran all test `suites.`
npm ERR! Test failed.  See above for more details.

### PR DESCRIPTION
**Pull request by VANKINEENITAWRUN**
Setting testURL in the jest config fixes the issue. fixes #8

### CODE REVIEW

**Comment by stevenzeck** [comment]
Hi @VANKINEENITAWRUN. I'd rather set the environment to use node, as mentioned here:
https://github.com/facebook/jest/issues/6766#issuecomment-408381957

**Comment by VANKINEENITAWRUN** [comment]
@stevenzeck node version on Travis is not supporting it.
just changing the line Travis shows
> FAIL  __tests__/index.test.js
  ● Test suite failed to run
    /home/travis/build/stevenzeck/issue-complete/node_modules/probot/lib/index.js:51
          ...event,
          ^^^
    SyntaxError: Unexpected token ...

**Comment by VANKINEENITAWRUN** [comment]
@stevenzeck update the node version in Travis. I checked on my development Machine with node 10.13.0 it works perfectly well.

**Comment by stevenzeck** [comment]
Hi @VANKINEENITAWRUN, there were quite a few things that had to be updated when I moved from probot 6.x to probot 7.x.  Running test from master now should work as expected.  Thanks for your contribution!

**Pull request closed without merging**
